version: '3.8'

services:
  rship-skaarhoj:
    build: .
    environment:
      - RSHIP_ADDRESS=${RSHIP_ADDRESS:-nyc.rship.io}
      - RSHIP_PORT=${RSHIP_PORT:-5155}
      - PANEL_ADDRESS=${PANEL_ADDRESS:-localhost}
      - PANEL_PORT=${PANEL_PORT:-9923}
      - RUST_LOG=${RUST_LOG:-info}
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/data
    depends_on: []
