services:
  videohub:
    build: .
    environment:
      - RSHIP_ADDRESS=${RSHIP_ADDRESS:-nyc.rship.io}
      - RSHIP_PORT=${RSHIP_PORT:-5155}
      - VIDEOHUB_ADDRESS=${VIDEOHUB_ADDRESS:-localhost}
      - VIDEOHUB_PORT=${VIDEOHUB_PORT:-9990}
      - RUST_LOG=${RUST_LOG:-info}
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/data
    depends_on: []
