name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Lint, Test & Build
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2
    
    - name: Check formatting
      run: cargo fmt --all -- --check
      
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Build release
      run: cargo build --verbose --release

    - name: Build docker
      run: docker build -t ghcr.io/ignition-is-go/rship-blackmagic-videohub:latest .

    - name: Login docker
      run: echo $GITHUB_TOKEN | docker login ghcr.io -u workflow --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish docker
      run: docker push ghcr.io/ignition-is-go/rship-blackmagic-videohub:latest
